### ISSUE TITLE
Failed to connect to localhost after depoy stack

### ISSUE THREAD

**Issue by akkien** [vincentserpoul/parityPoA#3]
Hi vincentserpoul, I trying to using your project. But after I start docker stack, I cannot connect to Node through RPC and this is error message: 
- Command: curl --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
- Error: curl: (7) Failed to connect to localhost port 8545: Connection refused

This is my step of create network:
1) ./generate.sh
2) ./build_docker_image.sh
3) cd docker-swarm
4) docker swarm init
5) ./create_configs_secrets.sh
6) ./launch_docker_stack.sh
The output after each step is OK but I still cannot connect using RPC.

Thank for your project.

**Comment by akkien** [comment]
[**Updated**]
This is error message from poa stack: "create poa_chain_A: missing required option: "device""
I don't know what it is. When I search for device option in compose file (https://docs.docker.com/compose/compose-file/#devices), the page say: The devices option is ignored when deploying a stack in swarm mode

**Comment by vincentserpoul** [comment]
@akkien this repo is using older version of parity and swarm, compose. I've not updated it for a while.
Actually, using parity these days might not be the best choice and I would suggest to take a look at geth for PoA setup.
I will add some warning at the beginning of the README to make this clear.

**Comment by akkien** [comment]
@vincentserpoul Thank you for your answer. I modified the code from docker swarm to docker-compose. For now, it works fine.

**Comment by vincentserpoul** [comment]
glad to hear that!
